disabled     = false
languageCode = "en"
languageName = "English"
weight       = 1
title        = "Evans' Whimsical Thoughts"

[params]
displayName = "EN"
isoCode     = "en"
rtl         = false
dateFormat  = "Jan 2, 2006"
description = "A blog about code, games, and life."
copyright   = "© { year } Evans' Whimsical Thoughts"

[params.author]
name     = "LeafEvans"
email    = "leafevans@foxmail.com"
image    = "img/author.jpg"
headline = "Endurance is not giving up. It's about staying strong and keeping your head up."
bio      = "An OCD patient, a perennial slacker, occasionally serious, and forever learning weakling."
links    = [
    { email     = "mailto:leafevans@foxmail.com" },
    { github    = "https://github.com/LeafEvans" },
    { reddit    = "https://reddit.com/user/LeafEvans" },
    { steam     = "https://steamcommunity.com/profiles/76561199536968532" },
    { x-twitter = "https://twitter.com/AliceLeaf218017" },
]
