disabled     = false
languageCode = "zh-cn"
languageName = "简体中文"
weight       = 1
title        = "Evans' Whimsical Thoughts"

[params]
displayName = "中文"
isoCode     = "zh-cn"
rtl         = false
dateFormat  = "2006年1月2日"
description = "一个偶尔正经、持续学习的弱鸡。博客内容随机掉落：代码、游戏、以及一些关于如何更好地忍耐生活的思考。"
copyright   = "© { year } Evans' Whimsical Thoughts"

[params.author]
name     = "LeafEvans"
email    = "leafevans@foxmail.com"
image    = "img/author.jpg"
headline = "忍，不是认输。忍耐就是要，想得开，挺得住。"
bio      = "An OCD patient, a perennial slacker, occasionally serious, and forever learning weakling."
links    = [
    { email     = "mailto:leafevans@foxmail.com" },
    { github    = "https://github.com/LeafEvans" },
    { reddit    = "https://reddit.com/user/LeafEvans" },
    { steam     = "https://steamcommunity.com/profiles/76561199536968532" },
    { x-twitter = "https://twitter.com/AliceLeaf218017" },
]
