[[main]]
name = "首页"
pageRef = "/"
weight = 1
title = "首页"

[[main]]
name = "随笔"
pageRef = "posts"
weight = 10
title = "随笔"

[[main]]
name = "分类"
pageRef = "categories"
weight = 20
title = "分类"

[[main]]
name = "标签"
pageRef = "tags"
weight = 30
title = "标签"

[[footer]]
name = "关于"
pageRef = "about"
weight = 10

[[footer]]
name = "联系"
url = "mailto:leafevans@foxmail.com"
weight = 20
