[[main]]
name    = "Home"
pageRef = "/"
weight  = 1
title   = "Home"

[[main]]
name    = "Posts"
pageRef = "posts"
weight  = 10
title   = "Posts"

[[main]]
name    = "Categories"
pageRef = "categories"
weight  = 20
title   = "Categories"

[[main]]
name    = "Tags"
pageRef = "tags"
weight  = 30
title   = "Tags"

[[footer]]
name    = "About"
pageRef = "about"
weight  = 10

[[footer]]
name    = "Contact"
url     = "mailto:leafevans@foxmail.com"
weight  = 20
